name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        crystal: [nightly]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global column.ui always
          git config --global core.autocrlf false

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Mercurial
        run: pip install mercurial

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run specs
        run: make test

      - name: Check formatting
        run: crystal tool format --check src spec

      - name: go sus
        run: |
          mkdir crystal
          cp -r bin/* crystal/
      - name: Upload Crystal binaries
        uses: actions/upload-artifact@v2
        with:
          name: crystal
          path: crystal
